include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    avoid_unnecessary_containers: true
    use_key_in_widget_constructors: true
    use_decorated_box: true
    avoid_redundant_argument_values: true
    unnecessary_string_interpolations: true
    unnecessary_brace_in_string_interps: true
    cascade_invocations: true
    prefer_spread_collections: true
    avoid_returning_null_for_void: true
    unnecessary_this: true
    prefer_typing_uninitialized_variables: true
    sort_child_properties_last: true
    use_super_parameters: true

